### PR TITLE
Added option to specify timeouts

### PR DESCRIPTION
**Pull request by ProjectInitiative**
Request to add the ability to specify read and write timeouts. Currently the library has hard-coded values for these timeouts. I added a constructor that allows for these values to be specified.

This constructor provides optional defaults for those values, but it can be adapted to follow the cascading constructor style like the other constructors.

### CODE REVIEW

**Comment by ProjectInitiative** [comment]
I noticed this when I was trying to use the library to scan for traffic on different, unknown COM devices. The problem came up when the Write command never finished Writing a message to a COM port. Instead of the Write method timing out, the library just waited indefinitely. I think adding the ability to change the timeout would be a useful addition!

**Comment by ProjectInitiative** [comment]
I fixed some house keeping things (removed files and the packages folder that shouldn't be checked in). They were causing build issues on other's machines. Also added a constructor for the option on the SerialPortInput.cs class.

**Comment by JTrotta** [comment]
It's a good idea. 
Did you made any test?
Does it work?

I cannot test it right now.

**Comment by ProjectInitiative** [comment]
I have not made any formal tests. However, it is has been implemented and packed and works using .NET core on Windows and Linux from what I have been seeing. Adding the timeouts did solve the weird hanging I got on some of the COM ports Windows would have that were either zombie ports, or dead in general.

**Comment by ProjectInitiative** [comment]
That being said, I would like to add that this should not break anyone's implementation since the new constructor arguments are optional!

**Comment by JTrotta** [comment]
Well done

**Pull request merged**
