### PR TITLE
Change Library to target .Net Standard

### PR DESCRIPTION
**Pull request by huserben**
Recreated project file to target .Net Standard.
Include .Net Standard compatible nuget packages Microsoft.Windows.Compatibility to access registry and Mono.Posix.NETStandard to access the SerialPorts on non Windows Devices.
Remove AssemblyInfo as not supported anymore.

I tried using your library on a Raspberry Pi for a Asp.Net Core application within a docker container. As it did not target .NET Standard it wasn't working out of the box, so I gave it a look and it was rather easy to target .Net Standard which makes it easy to use within containers on any OS.

It would be nice if you could integrate this so I could use the nuget package rather than the compiled dll in my project.

I added the nuget reference to the Mono.Posix.NETStandard because it's needed when running.
Probably it's better if the nuget itself has a dependency on this package (I'm not entirely sure how the nuget gets created and how the dependencies are figure out).

### CODE REVIEW

**Comment by JTrotta** [comment]
@huserben ,Ok and thank you for you work. But did you test it on Mono? Is it still working?
I'm still using mono as far as dotnetcore will be definitely stable and full of features.
If you confirm the library  will work both on Mono and core, it's OK for me to publish it on nuget.

Thank you

**Comment by huserben** [comment]
@JTrotta 

According to my understanding it should not be a problem to run it in a Mono Environment because Mono is .Net Standard 2.0 compliant (see also here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard).
However you are right I have not tested myself and it should definetly be done before.

I'm not an expert, could you tell me how I can verify this in a Mono Environment easily?

**Comment by JTrotta** [comment]
@huserben mmmhhh, not so easy if you do not have any experience. Basically you should install mono, and test one of the simply test project. But installing mono is not easy, let's try:

- update and upgrade you raspbian 
- get keys: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- install mono: sudo apt-get install mono-complete

If everything goes right (good luck), you could test  one of the simply test apps included. Obviously you should have some serial device to test on.

Let me know.

**Comment by huserben** [comment]
Thanks for the help, I will give it a try in the coming days and let you know whether I succeeded or not.

**Comment by huserben** [comment]
@JTrotta 

I created a tiny sample Console App to test it on Windows with the full .NET Framework and on my Linux Laptop with the Mono Complete package, where I tried to send and receive data from my connected Arduino: 

grafik
grafik

Everything worked fine, the key is just that the integrating projects **must** include the two nuget dependencies ([Microsoft.Windows.Compatibility](https://www.nuget.org/packages/Microsoft.Windows.Compatibility) and [Mono.Posix.NETStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard/)), so I updated the readme with that notice.
However when creating the nuget package it should be included as dependency and then you don't have to care about this. I couldn't see how the nuget is created so I couldn't verify if it's added as dependency automatically or if it needs some manual change there as well.  

Also if you're interested in the sample test application let me know, then I could add it to the solution as well. As I wasn't sure exactly what the existing Test Apps do and they had some hardcoded port names I opted to create a more generic console app for my tests to not have to recompile for the different targets (as Windows and Linux use different names for my Arduino)

**Comment by JTrotta** [comment]
Ok merged. The only problem is that now it should be renamed from MonoSerialPort to SharpSerialPort :->
I will compile and upload to nuget it minutes.

**Comment by huserben** [comment]
> Ok merged. The only problem is that now it should be renamed from MonoSerialPort to SharpSerialPort :->

True that =)

Thanks for merging, I'll try out the new package once it's available

**Pull request merged**
